# Generated by Django 5.2.9 on 2026-01-08 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='albumitem',
            name='collection',
        ),
        migrations.AddField(
            model_name='albumitem',
            name='album_page',
            field=models.ForeignKey(blank=True, help_text='Select the album page to link', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.albumpage'),
        ),
        migrations.AddField(
            model_name='albumitem',
            name='thumbnail',
            field=models.ForeignKey(blank=True, help_text='Album cover image (16:9 recommended)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
    ]
