# Generated by Django 5.2.9 on 2026-01-09 08:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_albumitem_collection_albumitem_album_page_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='news_page',
            field=models.ForeignKey(blank=True, help_text='Select the page that shows all news', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.newspage'),
        ),
    ]
