# Generated by Django 5.2.9 on 2026-01-09 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homepage_news_page'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='news_page',
        ),
    ]
